test:
  name: certificate-benchmark-test
  description: Benchmark for issuing, verifying, querying, and revoking certificates on Hyperledger Fabric.
  workers:
    type: local
    number: 1
  rounds:
    - label: Issue Certificates
      description: Issuing new certificates (using CreateAsset).
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: workload/issueCertificate.js

    - label: Verify a Certificate
      description: Verifying certificates exist (using ReadAsset).
      txDuration: 15
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: workload/verifyCertificate.js

    - label: Query All Certificates
      description: Browsing all certificates (using GetAllAssets).
      txDuration: 15
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: workload/queryAllCertificates.js

    - label: Revoke Certificate
      description: Revoking/Deleting certificates (using DeleteAsset).
      txDuration: 15
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: workload/revokeCertificate.js
