name: Fabric Certificate Benchmark
version: "2.0.0"
caliper:
  blockchain: fabric
channels:
  - channelName: mychannel
    contracts:
      - id: basic
organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: 'REPLACE_WITH_KEY_PATH'
          clientSignedCert:
            path: 'REPLACE_WITH_CERT_PATH'
    connectionProfile:
      path: 'networks/connection-org1.yaml'
      discover: false
